### ISSUE TITLE
no display name and no $DISPLAY environment variable

### ISSUE THREAD

**Issue by Suzansb** [trsvchn/coco-viewer#66]
Showing the following error:
`INFO: Starting...
Traceback (most recent call last):
  File "./coco-viewer/cocoviewer.py", line 898, in <module>
    main()
  File "./coco-viewer/cocoviewer.py", line 877, in main
    root = tk.Tk()
  File "/usr/lib/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable`

**Comment by trsvchn** [comment]
Hello @Suzansb!

`Tkinter` sees no display/window system, and can't start the GUI.

Do you run `cocoviewer` over ssh?

if so, use `-X` flag.
